#!/usr/bin/env python3
"""Embed a UTF-8 text file as C string data in a generated header.

With no symbol, the historical metagrammar macro is emitted. Named outputs
use a static array so large resources do not become one preprocessor line.

Usage: embed_metagrammar.py <input> <output.h> [symbol]
"""
import os
import sys


def main() -> int:
    if len(sys.argv) not in (3, 4):
        print("usage: embed_metagrammar.py <input> <output.h> [symbol]",
              file=sys.stderr)
        return 1
    in_path, out_path = sys.argv[1], sys.argv[2]
    symbol = (sys.argv[3] if len(sys.argv) == 4
              else "N00B_AUDIT_RULE_FILE_METAGRAMMAR")
    as_array = len(sys.argv) == 4
    with open(in_path, "rb") as fh:
        src = fh.read().decode("utf-8")
    lines = src.split("\n")
    n = len(lines)
    out_lines = [
        "#pragma once",
        "",
        "/* Auto-generated by scripts/embed_metagrammar.py from",
        f" * {os.path.basename(in_path)} — do not edit. */",
        "",
        (f"static const char {symbol}[] ="
         if as_array else f"#define {symbol} \\"),
    ]
    for i, line in enumerate(lines):
        esc = line.replace("\\", "\\\\").replace("\"", "\\\"")
        suffix = "\\n" if i + 1 < n else ""
        cont = "" if as_array else (" \\" if i + 1 < n else "")
        out_lines.append("    \"" + esc + suffix + "\"" + cont)
    if as_array:
        out_lines.append(";")
    out_lines.append("")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out_lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
